baseURL = "https://openbangla.github.io"
languageCode = "en-us"
title = "OpenBangla"
theme = "beautifulhugo"
disqusShortname = "openbangla"
googleAnalytics = "UA-83035690-1"

[Params]
  logo = "img/square.png"
  favicon = "img/openbangla.ico"
  dateFormat = "January 2, 2006"
  #commit = false
  rss = true
  comments = true
  readingTime = true
  useHLJS = true

[Author]
  name = "OpenBangla Team"
  website = "https://openbangla.github.io"
  email = "openbanglateam@gmail.com"
  facebook = "openbanglakeyboard"
  github = "OpenBangla"
  twitter = "OpenBanglaTeam"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Download"
    url = "download/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 3

[[menu.main]]
    name = "Github"
    url = "https://github.com/OpenBangla"
    weight = 4
